# Generated by Django 5.1.3 on 2024-12-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0004_member_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='Username',
        ),
    ]
